//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchPad.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sync_Appointments
    {
        public int Native_ID { get; set; }
        public Nullable<System.DateTime> Native_UpdateDt { get; set; }
        public Nullable<System.DateTime> Native_ImportDt { get; set; }
        public string Sync_UserEmail { get; set; }
        public string Sync_FolderPath { get; set; }
        public Nullable<bool> Sync_IsDeleted { get; set; }
        public Nullable<System.DateTime> Sync_ServerLastModified { get; set; }
        public Nullable<System.DateTime> Sync_ToServerDt { get; set; }
        public Nullable<System.DateTime> Sync_FromServerDt { get; set; }
        public Nullable<int> Sync_ServerResult { get; set; }
        public Nullable<int> Sync_ServerChangeType { get; set; }
        public string Sync_ID { get; set; }
        public string Sync_Error { get; set; }
        public string Sync_Apt_Attendees { get; set; }
        public Nullable<bool> Sync_Apt_IsOrganizer { get; set; }
        public Nullable<bool> Sync_Apt_ShouldSend { get; set; }
        public string Sync_Apt_OccuranceMaster { get; set; }
        public Nullable<int> Sync_Apt_OccuranceIndex { get; set; }
        public Nullable<int> Sync_Apt_OccuranceCount { get; set; }
        public Nullable<bool> IsMeeting { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string Recurrence { get; set; }
        public string FirstOccurrence { get; set; }
        public string LastOccurrence { get; set; }
        public string StartTimeZone { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<bool> IsAllDayEvent { get; set; }
        public string Location { get; set; }
        public string Sensitivity { get; set; }
        public string AppointmentType { get; set; }
        public Nullable<int> AppointmentState { get; set; }
        public string LastModifiedName { get; set; }
        public string MyResponseType { get; set; }
        public Nullable<int> ReminderMinutesBeforeStart { get; set; }
        public string Organizer { get; set; }
        public string RequiredAttendees { get; set; }
        public string OptionalAttendees { get; set; }
        public Nullable<int> Duration { get; set; }
        public string TimeZone { get; set; }
        public string ICalUid { get; set; }
        public string Id { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public string Categories { get; set; }
        public string Importance { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string UniqueBody { get; set; }
        public byte[] StoreEntryId { get; set; }
        public string TextBody { get; set; }
        public Nullable<int> Launchpad_ID { get; set; }
    }
}
